import {
    Loader2,
    Sun,
    Moon,
    Check,
    Calendar,
    Home,
    Inbox,
    Search,
    Settings,
    BrainCircuit,
    Bell,
    X,
    Send,
    CircleUser,
    Store,
    ReceiptText,
    ReceiptEuro,
    Folder,
    ChevronDown,
    ChevronRight,
    HandCoins,
    ListCheck,
    ListTodo,
    SquareCheck,
    LayoutList,
    SquarePlus,
    ShoppingBasket,
    ShoppingCart,
    Mail,
    Gamepad2, LaptopMinimalCheck, ChromeIcon, Lightbulb, UsersRound, BadgeCheck, Eye,
    Facebook
} from "lucide-react";

export const Icons = {
    spinner: Loader2,
    sun: Sun,
    moon: Moon,
    check: Check,
    calendar: Calendar,
    home: Home,
    inbox: Inbox,
    search: Search,
    settings: Settings,
    brain: BrainCircuit,
    bell: Bell,
    close: X,
    send: Send,
    circleUser: CircleUser,
    store: Store,
    receiptText: ReceiptText,
    folder: Folder,
    chevronDown: ChevronDown,
    handCoins: HandCoins,
    receiptEuro: ReceiptEuro,
    listTodo: ListTodo,
    listCheck: ListCheck,
    squareCheck: SquareCheck,
    layoutList: LayoutList,
    squarePlus: SquarePlus,
    shoppingBasket: ShoppingBasket,
    shoppingCart: ShoppingCart,
    chevronRight: ChevronRight,
    mail: Mail,
    gamePad2: Gamepad2,
    laptopMinimalCheck: LaptopMinimalCheck,
    chrome: ChromeIcon,
    lightbulb: Lightbulb,
    usersRound: UsersRound,
    badgeCheck: BadgeCheck,
    eye: Eye,
    facebook: Facebook
}